### ISSUE TITLE
Fix up Header and Footer

### ISSUE THREAD

**Issue by kbourbery** [Watt-Esports/wattesports.co.uk#43]
- Give header a drop shadow
- Have header stick to top of page all the time
- Have footer kept to bottom of page all the time
- Use Watt Esports logo (and Discord logo?) in header

**Comment by KommToby** [comment]
After a quick lookaround, for the 

> Have footer kept to bottom of page all the time

I can't change any of the css for the bootstrap link or whatever because i've never used it before, so again this is going to have to be an @Nicolauze fix

**Comment by Simber1** [comment]
> Have footer kept to bottom of page all the time  

Looking at about this seems to already be the case.

**Comment by KommToby** [comment]
> > Have footer kept to bottom of page all the time
> 
> Looking at about this seems to already be the case.

perhaps this was worded badly; I meant keep the footer at the very, very bottom of the page. Not for it to hover at the bottom of your window wherever you scroll
#75 resolves this anyways, but that's only the footer. Still need to work on the other stuff

**Comment by KommToby** [comment]
I managed to add a drop shadow to the header, it looks kind of clunky because of how drop shadows work they go at an angle.

![image](https://user-images.githubusercontent.com/12158645/81255245-1a70a100-9025-11ea-960d-3f6db3e4c521.png)

Click on image above to see what I mean, the bottom left corner is left without shadow, It doesn't look nice. I think we should skip the drop shadow on the header

EDIT:
Turns out people prefer this, so i'll implement it

**Comment by Simber1** [comment]
> I managed to add a drop shadow to the header, it looks kind of clunky because of how drop shadows work they go at an angle.  

Played around with this a little bit and I think it looks better without.
